### ISSUE TITLE
Handle page element references

### ISSUE THREAD

**Issue by webignition** [webignition/basil-dom-identifier-factory#27]
Previously:

```yaml
url: https://example.com
elements:
  form: '$".form"'
  input: '$"{{ form }} .input"'
```

Now:
```yaml
url: https://example.com
elements:
  form: '$".form"'
  input: '$form >> $".input"'
```
